---
name: "Parse chart URI"
description: |
  Extracts the chart URI parts from a given chart URI.
  The chart URI should be in the format `repository/name:version`.
  For example: `ghcr.io/my-org/my-repo/charts/my-application/my-repo:0.1.0`.
  The output will be:

  - `repository`: `ghcr.io/my-org/my-repo/charts/my-application`
  - `name`: `my-repo`
  - `version`: `0.1.0`
author: hoverkraft
branding:
  icon: link
  color: blue

inputs:
  uri:
    description: "Chart URI to parse."
    required: true

outputs:
  repository:
    description: "Repository part of the chart URI."
    value: ${{ steps.parse-chart-uri.outputs.repository }}
  name:
    description: "Name part of the chart URI."
    value: ${{ steps.parse-chart-uri.outputs.name }}
  version:
    description: "Version part of the chart URI."
    value: ${{ steps.parse-chart-uri.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: parse-chart-uri
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const chartUri = ${{ toJSON(inputs.uri) }};
          if (!chartUri.length) {
            return core.setFailed("Input 'uri' is required.");
          }

          const regex = /^(.*)\/(.+):(.*)$/;
          const match = chartUri.match(regex);
          if (!match) {
            return core.setFailed(`Invalid chart URI format: ${chartUri}`);
          }

          const [_, repository, name, version] = match;
          core.setOutput("repository", repository);
          core.setOutput("name", name);
          core.setOutput("version", version);
