name: Internal - Generate dependabot.yml config

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  generate-dependabot-config:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/generate-dependabot-config.yml@0.13.2
    with:
      github-app-id: ${{ vars.CI_BOT_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
