name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    branches: [main]

permissions: {}

jobs:
  greetings:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@6a0fdae9e2598eccf7a9ec2bc20e7ce8e7c10c48 # 0.36.4
    permissions:
      contents: read
      issues: write
      pull-requests: write
