---
name: "Pull Request - Semantic Lint"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@59c06291a1619e383a38f2006f15627aa528bb95 # 0.37.0
    permissions:
      contents: write
      pull-requests: write
