---
name: "Pull Request - Semantic Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@cacc6123a32780d507db04733e5a8c167917581d # 0.35.3
    permissions:
      contents: write
      pull-requests: write
