---
name: "Pull Request - Semantic Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@03a5a2a3626b03434b19b79cdd2e141bea410bae # 0.34.1
    permissions:
      contents: write
      pull-requests: write
