---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@4c9d51717dc04d823dac2dc9ac2857e7b3069454 # 0.35.0
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write

  test-action-docker-build-image:
    needs: linter
    uses: ./.github/workflows/__test-action-docker-build-image.yml
    permissions:
      contents: read
      packages: write

  test-action-docker-prune-pull-requests-package-version:
    needs: linter
    # yamllint disable-line rule:line-length
    uses: ./.github/workflows/__test-action-docker-prune-pull-requests-image-tags.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read

  test-action-get-image-metadata:
    needs: linter
    uses: ./.github/workflows/__test-action-get-image-metadata.yml
    permissions:
      contents: read

  test-action-action-get-image-name:
    needs: linter
    uses: ./.github/workflows/__test-action-get-image-name.yml
    permissions:
      contents: read

  test-action-helm-parse-chart-uri:
    needs: linter
    uses: ./.github/workflows/__test-action-helm-parse-chart-uri.yml
    permissions:
      contents: read

  test-action-helm-release-chart:
    needs: linter
    uses: ./.github/workflows/__test-action-helm-release-chart.yml
    permissions:
      contents: read
      packages: write

  test-action-helm-test-chart:
    needs: linter
    uses: ./.github/workflows/__test-action-helm-test-chart.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read

  test-workflow-docker-build-images-building:
    name: Test docker build images - Building
    needs: linter
    uses: ./.github/workflows/__test-workflow-docker-build-images-building.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets: inherit

  test-workflow-docker-build-images-caching:
    name: Test docker build images - Caching
    needs: linter
    uses: ./.github/workflows/__test-workflow-docker-build-images-caching.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets: inherit

  test-workflow-docker-build-images-multi-registry:
    name: Test docker build images - Multi registry inputs
    needs: linter
    uses: ./.github/workflows/__test-workflow-docker-build-images-multi-registry.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets: inherit

  test-workflow-docker-build-images-platforms-and-signing:
    name: Test docker build images - Platforms and Signing
    needs: linter
    uses: ./.github/workflows/__test-workflow-docker-build-images-platforms-and-signing.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets: inherit
