---
name: Mark stale issues and pull requests

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/stale.yml@cacc6123a32780d507db04733e5a8c167917581d # 0.35.3
    permissions:
      issues: write
      pull-requests: write
