---
name: Mark stale issues and pull requests

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/stale.yml@6a0fdae9e2598eccf7a9ec2bc20e7ce8e7c10c48 # 0.36.4
    permissions:
      issues: write
      pull-requests: write
