name: Test for "docker/delete-image-tags" action
run-name: Test for "docker/delete-image-tags" action

on:
  workflow_call:

env:
  IMAGE: "test-delete-image-tags"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      - run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GitHub token secrets is not set"
            exit 1
          fi
      - id: generate-tag
        run: |
          RC="-rc.${{ github.run_number }}"
          TAG="$(printf '%d.%d.%d%s' $((1+RANDOM%20)) $((1+RANDOM%20)) $((1+RANDOM%20)) "$RC")"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

  arrange:
    needs: setup
    uses: ./.github/workflows/docker-build-images.yml
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      images: |
        [
          {
            "name": "test-delete-image-tags",
            "context": ".",
            "dockerfile": "./tests/application-1/Dockerfile",
            "build-args": { "PROD_MODE": "true" },
            "target": "prod",
            "platforms": ["linux/amd64"],
            "tag": "${{ needs.setup.outputs.tag }}"
          }
        ]

  act-and-assert:
    name: Test for "delete-image-tags" action
    runs-on: ubuntu-latest
    needs: [setup, arrange]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - id: delete-image-tags
        uses: ./actions/docker/delete-image-tags
        with:
          image: ${{ env.IMAGE }}
          tag-prefix: ${{ needs.setup.outputs.tag }}

      - name: Check ouputs
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const assert = require("assert");

            const deletedImageTagsOutput = `${{ steps.delete-image-tags.outputs.deleted-image-tags }}`;
            assert(deletedImageTagsOutput.length, `"deleted-image-tags" output is empty`);

            // Check if is valid Json
            let deletedImageTags = null;
            try {
              deletedImageTags = JSON.parse(deletedImageTagsOutput);
            } catch (error) {
              throw new Error(`"deleted-image-tags" output is not a valid JSON: ${error}`);
            }

            assert(Array.isArray(deletedImageTags), `"deleted-image-tags" output is not an array`);
            assert.deepEqual(deletedImageTags, ["${{ needs.setup.outputs.tag }}"]);

      - name: Ensure packages have been deleted
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ github.token }}
          script: |
            const assert = require("assert");
            const packagePayload = {
              package_type: 'container',
              package_name: 'ci-github-container/${{ env.IMAGE }}',
              org: 'hoverkraft-tech',
            };

            const packageVersions = await github.paginate(
              github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg.endpoint.merge(packagePayload)
            );

            const packageVersionExists = packageVersions.some(
              (packageVersion) => packageVersion.metadata.container.tags.some(
                (tag) => tag === "${{ needs.setup.outputs.tag }}"
              )
            );
            assert.equal(packageVersionExists, false, `Package version "${{ needs.setup.outputs.tag }}" has not been deleted`);
