---
name: Test for "helm/test-chart" action
run-name: Test for "helm/test-chart" action

on:
  workflow_call:

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
  id-token: write

jobs:
  build-test-images:
    uses: ./.github/workflows/docker-build-images.yml
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      images: |
        [
          {
            "name": "application-test",
            "context": ".",
            "dockerfile": "./tests/application/Dockerfile",
            "build-args": { "BUILD_RUN_ID": "${{ github.run_id }}" },
            "target": "prod",
            "platforms": ["linux/amd64"],
            "tag": "0.1.0"
          }
        ]

  test-lint-and-install:
    name: Test for "helm/test-chart" action
    needs: build-test-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: test-chart
        uses: ./actions/helm/test-chart
        with:
          enable-lint: false # FIXME: remove
          check-diff-only: false
          helm-set: |
            image.tag=0.1.0
          helm-repositories: |
            bitnami https://charts.bitnami.com/bitnami
          oci-registry: ghcr.io
          oci-registry-username: ${{ github.actor }}
          oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  # test-with-private-image:
  #   name: Test for "helm/test-chart" action with private image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - id: get-image-metadata
  #       uses: ./actions/docker/get-image-metadata
  #       with:
  #         oci-registry: ghcr.io
  #         image: private-application-test

  #     - id: test-chart
  #       uses: ./actions/helm/test-chart
  #       with:
  #         helm-set: |
  #           image.tag=${{ steps.get-image-metadata.outputs.tags[0] }}
  #         helm-repositories: |
  #           bitnami https://charts.bitnami.com/bitnami
  #         oci-registry: ghcr.io
  #         oci-registry-username: ${{ github.actor }}
  #         oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
