---
name: Test for "helm/parse-chart-uri" action
run-name: Test for "actions/helm/parse-chart-uri" action

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  test:
    name: Test for "helm/parse-chart-uri" action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Act
        id: parse-chart-uri
        uses: ./actions/helm/parse-chart-uri
        with:
          uri: "ghcr.io/my-org/my-repo/charts/application/my-repo:0.1.0"

      - name: Assert - Check parse chart URI ouputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          REPOSITORY_OUTPUT: ${{ steps.parse-chart-uri.outputs.repository }}
          NAME_OUTPUT: ${{ steps.parse-chart-uri.outputs.name }}
          VERSION_OUTPUT: ${{ steps.parse-chart-uri.outputs.version }}
        with:
          script: |
            const assert = require("assert");

            const repositoryOutput = process.env.REPOSITORY_OUTPUT;
            assert.equal(repositoryOutput,"ghcr.io/my-org/my-repo/charts/application", `"repository" output is not valid`);

            const nameOutput = process.env.NAME_OUTPUT;
            assert.equal(nameOutput,"my-repo", `"name" output is not valid`);

            const versionOutput = process.env.VERSION_OUTPUT;
            assert.equal(versionOutput,"0.1.0", `"version" output is not valid`);
